### PR TITLE
forEach to for

### PR DESCRIPTION
**Pull request by lifeart**
https://jsperf.com/foreach-vs-loop/43

### CODE REVIEW

**Comment by whoozle** [comment]
your test is from 2013, is it still the case? I'm not sure we can approve that without solid proof

**Comment by lifeart** [comment]
@whoozle 
image

**Comment by whoozle** [comment]
Unfortunately, this has absolutely no effect on real projects, since we rarely have more than 1-2 event listeners attached to the same event. I cannot accept it in this present state, sorry. Just to save your time, you can file an issue first, before doing any work or discuss it in our support channel. 

The only place I can think of (where this optimization could work out) is Context._processActions()

**Comment by whoozle** [comment]
I've replaced loops in _processActions as you suggested, since it's the only place which processes hundreds of iterations

0ac4f52e1c6e7abf8aaafb1efbb8aa0430cca496

**Comment by lifeart** [comment]
@whoozle `we rarely have more than 1-2 event listeners attached to the same event` - if you have 2000+ nodes, 2 listeners for each - this give us 4000 iterations

**Comment by whoozle** [comment]
They are not global and scattered across individual arrays

4 сент. 2017 г. 13:58 пользователь "Alex Kanunnikov" <
notifications@github.com> написал:

**Comment by whoozle** [comment]
moreover, we're talking about 2x performance boost (of values of -5 order of magnitude ) with total numbers as big as 42ms.

**Pull request closed without merging**
