### PR TITLE
local undefined, 20% faster

### PR DESCRIPTION
**Pull request by lifeart**
https://jsperf.com/type-of-undefined-vs-undefined

### CODE REVIEW

**Comment by whoozle** [comment]
20% faster of what? what did you test?

**Comment by lifeart** [comment]
@whoozle faster than global `undefined` comparison

**Comment by whoozle** [comment]
undefined is not a global, it's a primitive value

**Comment by lifeart** [comment]
@whoozle  
image

**Comment by whoozle** [comment]
did you actually test it on real code? synthetic tests are not really reliable

**Comment by lifeart** [comment]
@whoozle I'm profiling app
image

**Comment by whoozle** [comment]
Why do you think that it's undefined to blame, there's enabled () call too

**Comment by lifeart** [comment]
@whoozle take a look at 2nd string on screenshot

**Comment by whoozle** [comment]
Remember we're talking of 20% difference of values with 10¯⁸ order of magnitude. Moreover, first link shows that it's pre-59 chrome problem. 

We can't sacrifice readability/maintainability of our code for 0.2 * 10¯⁸ * 0.2 * 10¯³ cpu time improvement

**Pull request closed without merging**
